CONSUMER_KEY = 'AAAAAA'
CONSUMER_SECRET = 'BBBBBB'
ACCESS_KEY = 'CCCCCC'
ACCESS_SECRET = 'DDDDDD'


tweepy.OAuthHandler("CONSUMER_KEY","CONSUMER_SECRET")
set_access_token("ACCESS_KEY", "ACCESS_SECRET")
